name: clang-tidy

on: [ push, pull_request ]

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04

    env:
      CC: clang-18
      CXX: clang++-18
      LUA_VERSION: 5.4
      LUAJIT_OPTION: OFF
      POSTGRESQL_VERSION: 16
      POSTGIS_VERSION: 3
      BUILD_TYPE: Debug
      PSYCOPG: 3
      PIP_OPTION: --break-system-packages

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ubuntu-prerequisites
      - uses: ./.github/actions/linux-cmake
      - uses: ./.github/actions/clang-tidy

